### ISSUE TITLE
About "bidirectional = True", it seems something get wrong。please help。

### ISSUE THREAD

**Issue by zshy1205** [asappresearch/sru#177]
I test this code:
```import torch
from sru import SRU, SRUCell
x = torch.FloatTensor(20, 32, 128).cuda()

input_size, hidden_size = 128, 128

rnn = SRU(input_size, hidden_size,
    num_layers = 1,          # number of stacking RNN layers
    dropout = 0.0,           # dropout applied between RNN layers
    bidirectional = False,   # bidirectional RNN
    # layer_norm = False,      # apply layer normalization on the output of each layer
    # highway_bias = -2,        # initial bias of highway gate (<= 0)
)
for name in rnn.named_parameters():
    print(name[0], name[1].shape)
```
when I run this code，I can get the output is :
```
rnn_lst.0.weight torch.Size([128, 384])
rnn_lst.0.weight_c torch.Size([256])
rnn_lst.0.bias torch.Size([256])
```
but when I change the code to bidirectional = True，I get the output is:
```
rnn_lst.0.weight torch.Size([128, 1024])
rnn_lst.0.weight_c torch.Size([512])
rnn_lst.0.bias torch.Size([512])
```
Why rnn_lst.0.weight size from [128, 384] change to [128, 1024], Can you tell me? Thanks。

**Comment by taoleicn** [comment]
@zshy1205 

- the parameter `weight` has a shape `(input_size, output_size * num_matrices)` where `input_size` is the input dimension, `output_size` is the output dimension of SRU and `num_matrices` are the number of matrices & matrix multiplications needed for this layer. These matrix multiplications are grouped as a big batched matrix multi for a speed-up of the computation.

- `num_matrices` is 3 when `input_size = output_size`. i.e. you have one `W*x[t]` in the forget gate, one in the reset gate and the third one in `c[t] = f[t]*c[t-1] + (1-f[t]) * (W*x[t])`.

- when `input_size != output_size`, there will be one more matrix multiplication needed in the highway connection: `h[t] = r[t]*c[t] + (1-r[t]) * (W*x[t])` because the dimension of h[t] and x[t] are now different.


So in your case, there are two things happening:
1. when you use `bidirectional = True`, the output size of the SRU will be `128 * 2 = 256`;
2. because now the input size and output size are different, the num of matrices is 4.
So `128*2 * 4 = 1024`. That's why you see `rnn_lst.0.weight` has shape (128, 1024) now.

**Comment by taoleicn** [comment]
See https://github.com/asappresearch/sru/blob/master/sru/modules.py#L130-L142

**Comment by zshy1205** [comment]
@taoleicn Thanks.
